- name: Create tomcat group
  group:
    name: tomcat
    gid: 950
    state: present

- name: Create tomcat user
  user:
    name: tomcat
    uid: 950
    group: tomcat

- name: Create tomcat home directory
  file:
    path: "{{tomcat_home}}"
    state: directory

- name: Unarchive tomcat from remote source
  unarchive:
    src: "https://apache-mirror.rbc.ru/pub/apache/tomcat/tomcat-{{tomcat_version.split('.')[0]}}/v{{tomcat_version}}/bin/apache-tomcat-{{tomcat_version}}.tar.gz"
    dest: "{{tomcat_home}}"
    owner: tomcat
    group: tomcat
    remote_src: yes

- name: Setup Init
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  notify:
    - Tomcat restart

- name: Ensure tomcat running and enabled
  service:
    name: tomcat
    state: started
    enabled: yes