- hosts: all

  vars:
    mongo_version:
      "3.6"
    mongo_src:
      - mongodb-linux-x86_64-rhel64-3.0.14
      - mongodb-linux-x86_64-rhel64-3.2.11
      - mongodb-linux-x86_64-rhel70-3.0.14
      - mongodb-linux-x86_64-rhel70-3.2.17
      - mongodb-linux-x86_64-rhel70-3.4.13
      - mongodb-linux-x86_64-rhel70-3.6.3
      - mongodb-linux-x86_64-rhel70-3.7.2
      - mongodb-linux-x86_64-ubuntu1604-3.4.12
      - mongodb-linux-x86_64-ubuntu1604-3.4.13
      - mongodb-linux-x86_64-ubuntu1604-3.6.3
      - mongodb-linux-x86_64-ubuntu1604-3.7.2
      - mongodb-linux-x86_64-debian81-3.4.13
      - mongodb-linux-x86_64-debian81-3.2.19
      - mongodb-linux-x86_64-debian81-3.7.2
      - mongodb-linux-x86_64-rhel80-3.6.23
    mongo_url:
      "http://downloads.mongodb.org/linux/{{mongo_src | get_mongo_src(ansible_distribution, ansible_distribution_major_version, mongo_version)}}.tgz"

  tasks:
  - debug:
      msg: "Your url for download - {{mongo_url}}"